//
//  WordWolfTopic.swift
//  PartyGame
//
//  Created by GitHub Copilot on 2026/02/03.
//

import Foundation

struct WordWolfTopic: Codable, Identifiable {
    var id = UUID()
    let citizen: String
    let wolf: String
}

// 100 topics
let wordWolfTopics: [WordWolfTopic] = [
    WordWolfTopic(citizen: "りんご", wolf: "なし"),
    WordWolfTopic(citizen: "犬", wolf: "猫"),
    WordWolfTopic(citizen: "うどん", wolf: "そば"),
    WordWolfTopic(citizen: "海", wolf: "プール"),
    WordWolfTopic(citizen: "コーヒー", wolf: "紅茶"),
    WordWolfTopic(citizen: "焼肉", wolf: "ステーキ"),
    WordWolfTopic(citizen: "きのこの山", wolf: "たけのこの里"),
    WordWolfTopic(citizen: "ディズニーランド", wolf: "ディズニーシー"),
    WordWolfTopic(citizen: "おにぎり", wolf: "サンドイッチ"),
    WordWolfTopic(citizen: "野球", wolf: "サッカー"),
    WordWolfTopic(citizen: "マクドナルド", wolf: "モスバーガー"),
    WordWolfTopic(citizen: "醤油", wolf: "ソース"),
    WordWolfTopic(citizen: "夏", wolf: "冬"),
    WordWolfTopic(citizen: "映画館", wolf: "DVD鑑賞"),
    WordWolfTopic(citizen: "遊園地", wolf: "動物園"),
    WordWolfTopic(citizen: "ピアノ", wolf: "ギター"),
    WordWolfTopic(citizen: "ドラえもん", wolf: "クレヨンしんちゃん"),
    WordWolfTopic(citizen: "ご飯", wolf: "パン"),
    WordWolfTopic(citizen: "鉛筆", wolf: "シャープペンシル"),
    WordWolfTopic(citizen: "水族館", wolf: "美術館"),
    WordWolfTopic(citizen: "飛行機", wolf: "新幹線"),
    WordWolfTopic(citizen: "カレー", wolf: "シチュー"),
    WordWolfTopic(citizen: "スプーン", wolf: "フォーク"),
    WordWolfTopic(citizen: "チョコレート", wolf: "クッキー"),
    WordWolfTopic(citizen: "サンダル", wolf: "スニーカー"),
    WordWolfTopic(citizen: "テレビ", wolf: "YouTube"),
    WordWolfTopic(citizen: "メガネ", wolf: "コンタクトレンズ"),
    WordWolfTopic(citizen: "唐揚げ", wolf: "天ぷら"),
    WordWolfTopic(citizen: "自転車", wolf: "バイク"),
    WordWolfTopic(citizen: "エスカレーター", wolf: "エレベーター"),
    WordWolfTopic(citizen: "旅館", wolf: "ホテル"),
    WordWolfTopic(citizen: "扇風機", wolf: "エアコン"),
    WordWolfTopic(citizen: "朝", wolf: "夜"),
    WordWolfTopic(citizen: "太陽", wolf: "月"),
    WordWolfTopic(citizen: "警察官", wolf: "消防士"),
    WordWolfTopic(citizen: "医者", wolf: "看護師"),
    WordWolfTopic(citizen: "ライオン", wolf: "トラ"),
    WordWolfTopic(citizen: "お風呂", wolf: "シャワー"),
    WordWolfTopic(citizen: "トイレ", wolf: "洗面所"),
    WordWolfTopic(citizen: "枕", wolf: "クッション"),
    WordWolfTopic(citizen: "タオル", wolf: "ハンカチ"),
    WordWolfTopic(citizen: "漫画", wolf: "小説"),
    WordWolfTopic(citizen: "スマホ", wolf: "ガラケー"),
    WordWolfTopic(citizen: "パソコン", wolf: "タブレット"),
    WordWolfTopic(citizen: "みかん", wolf: "オレンジ"),
    WordWolfTopic(citizen: "ぶどう", wolf: "マスカット"),
    WordWolfTopic(citizen: "いちご", wolf: "さくらんぼ"),
    WordWolfTopic(citizen: "トマト", wolf: "ミニトマト"),
    WordWolfTopic(citizen: "キャベツ", wolf: "レタス"),
    WordWolfTopic(citizen: "大根", wolf: "カブ"),
    WordWolfTopic(citizen: "にんじん", wolf: "ごぼう"),
    WordWolfTopic(citizen: "わさび", wolf: "からし"),
    WordWolfTopic(citizen: "マヨネーズ", wolf: "ケチャップ"),
    WordWolfTopic(citizen: "塩", wolf: "砂糖"),
    WordWolfTopic(citizen: "バター", wolf: "マーガリン"),
    WordWolfTopic(citizen: "牛乳", wolf: "豆乳"),
    WordWolfTopic(citizen: "緑茶", wolf: "麦茶"),
    WordWolfTopic(citizen: "コーラ", wolf: "サイダー"),
    WordWolfTopic(citizen: "ショートケーキ", wolf: "チーズケーキ"),
    WordWolfTopic(citizen: "シュークリーム", wolf: "エクレア"),
    WordWolfTopic(citizen: "プリン", wolf: "ゼリー"),
    WordWolfTopic(citizen: "アイスクリーム", wolf: "ソフトクリーム"),
    WordWolfTopic(citizen: "ポテトチップス", wolf: "ポップコーン"),
    WordWolfTopic(citizen: "グミ", wolf: "アメ"),
    WordWolfTopic(citizen: "ガム", wolf: "タブレット菓子"),
    WordWolfTopic(citizen: "せんべい", wolf: "おかき"),
    WordWolfTopic(citizen: "あんこ", wolf: "クリーム"),
    WordWolfTopic(citizen: "たい焼き", wolf: "今川焼き"),
    WordWolfTopic(citizen: "お好み焼き", wolf: "たこ焼き"),
    WordWolfTopic(citizen: "焼きそば", wolf: "焼うどん"),
    WordWolfTopic(citizen: "ラーメン", wolf: "つけ麺"),
    WordWolfTopic(citizen: "パスタ", wolf: "ピザ"),
    WordWolfTopic(citizen: "ハンバーグ", wolf: "ミートボール"),
    WordWolfTopic(citizen: "餃子", wolf: "シューマイ"),
    WordWolfTopic(citizen: "春巻き", wolf: "生春巻き"),
    WordWolfTopic(citizen: "麻婆豆腐", wolf: "エビチリ"),
    WordWolfTopic(citizen: "チャーハン", wolf: "ピラフ"),
    WordWolfTopic(citizen: "オムライス", wolf: "親子丼"),
    WordWolfTopic(citizen: "牛丼", wolf: "豚丼"),
    WordWolfTopic(citizen: "カツ丼", wolf: "天丼"),
    WordWolfTopic(citizen: "うな重", wolf: "海鮮丼"),
    WordWolfTopic(citizen: "味噌汁", wolf: "コンソメスープ"),
    WordWolfTopic(citizen: "コーンスープ", wolf: "クラムチャウダー"),
    WordWolfTopic(citizen: "目玉焼き", wolf: "スクランブルエッグ"),
    WordWolfTopic(citizen: "ゆで卵", wolf: "温泉卵"),
    WordWolfTopic(citizen: "納豆", wolf: "豆腐"),
    WordWolfTopic(citizen: "キムチ", wolf: "漬物"),
    WordWolfTopic(citizen: "梅干し", wolf: "らっきょう"),
    WordWolfTopic(citizen: "海苔", wolf: "ふりかけ"),
    WordWolfTopic(citizen: "ジャム", wolf: "はちみつ"),
    WordWolfTopic(citizen: "ドレッシング", wolf: "ポン酢"),
    WordWolfTopic(citizen: "日本", wolf: "韓国"),
    WordWolfTopic(citizen: "アメリカ", wolf: "イギリス"),
    WordWolfTopic(citizen: "フランス", wolf: "イタリア"),
    WordWolfTopic(citizen: "東京", wolf: "大阪"),
    WordWolfTopic(citizen: "北海道", wolf: "沖縄"),
    WordWolfTopic(citizen: "富士山", wolf: "エベレスト"),
    WordWolfTopic(citizen: "Amazon", wolf: "楽天"),
    WordWolfTopic(citizen: "Google", wolf: "Yahoo"),
    WordWolfTopic(citizen: "iPhone", wolf: "Android")
]
